services:
  # sql:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sql
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: "Password@1"
  #   platform: "linux/amd64"
  #   ports:
  #     - "1433:1433"
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always
