// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenderFlow_AI.Infrastructure.Persistence;

#nullable disable

namespace TenderFlow_AI.Infrastructure.Migrations
{
    [DbContext(typeof(TenderFlowDbContext))]
    [Migration("20260301235531_AddDomainEntities")]
    partial class AddDomainEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.CompanyProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("TechnologiesUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CompanyProjects");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JiraGitConfluenceExperienceYears")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModernTechStackExperienceYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClassificationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinimumYearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Tender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPersonDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSoftwareDevelopers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Requirement", b =>
                {
                    b.HasOne("TenderFlow_AI.Domain.Entities.Tender", "Tender")
                        .WithMany("Requirements")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Tender", b =>
                {
                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
