// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenderFlow_AI.Infrastructure.Persistence;

#nullable disable

namespace TenderFlow_AI.Infrastructure.Migrations
{
    [DbContext(typeof(TenderFlowDbContext))]
    [Migration("20260302202055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.CompanyProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanyProjects");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.EmployeeSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeSkill");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.OrganizationContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTargetValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationContexts");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.ProjectAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompanyProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProjectId");

                    b.ToTable("ProjectAttribute");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MappingKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequirementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Tender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.TenderConstraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderConstraint");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.EmployeeSkill", b =>
                {
                    b.HasOne("TenderFlow_AI.Domain.Entities.Employee", null)
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.OrganizationContext", b =>
                {
                    b.HasOne("TenderFlow_AI.Domain.Entities.Organization", null)
                        .WithMany("ContextRules")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.ProjectAttribute", b =>
                {
                    b.HasOne("TenderFlow_AI.Domain.Entities.CompanyProject", null)
                        .WithMany("Attributes")
                        .HasForeignKey("CompanyProjectId");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Requirement", b =>
                {
                    b.HasOne("TenderFlow_AI.Domain.Entities.Tender", "Tender")
                        .WithMany("Requirements")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.TenderConstraint", b =>
                {
                    b.HasOne("TenderFlow_AI.Domain.Entities.Tender", null)
                        .WithMany("Constraints")
                        .HasForeignKey("TenderId");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.CompanyProject", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Organization", b =>
                {
                    b.Navigation("ContextRules");
                });

            modelBuilder.Entity("TenderFlow_AI.Domain.Entities.Tender", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
